### PR TITLE
[BUGFIX] Fix composer.json

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@simonschaufi What is the reason for that?

**Comment by simonschaufi** [comment]
it's duplicated now

**Comment by sabbelasichon** [comment]
What do you mean with duplicated?

**Comment by simonschaufi** [comment]
see https://github.com/andreaswolf/fractor/blob/main/composer.json#L41-L60

**Comment by sabbelasichon** [comment]
Normally it should not be necessary to manually fix this.

**Comment by simonschaufi** [comment]
You were a bit too fast with merging https://github.com/andreaswolf/fractor/pull/109 as I wanted to extract that as I realized that the root composer.json is not covered by the CI atm.

**Comment by simonschaufi** [comment]
> vendor/bin/monorepo-builder merge

this should be documented somewhere

**Pull request merged**
